### ISSUE TITLE
Typo in composer.json

### ISSUE THREAD

**Issue by liberatomota-itcenter** [bmwcarit/silex-jira-oauth-provider#1]
Hello,
First, thank you for creating this package.

Instaling with composer is giving this error:
bmwcarit/silex-jira-oauth-provider dev-master requires guzzlehttp/oauth-subscriber >0.2 -> no matching package found.

In your composer file you have guzzlehttp/oauth-subscriber >0.2.
Composer is not accepting this.
Can you tell me if  is a typo or something in the guzzlehttp package?

Thank you

**Comment by elmi82** [comment]
Hi,

thank you for spotting this. Setting your minimum-stability to "dev" will fix this.

```
{
    "name": "acme/hello-world",
    "minimum-stability": "dev",
    "require": {
        "bmwcarit/silex-jira-oauth-provider": "dev-master"
    }
}
```

The oauth-provider has a [fix](https://github.com/guzzle/oauth-subscriber/commit/55c001f5cbcfab5f44792426538cba5bd53168f2) that was made after the 0.2 release, that is required if you use a private key file. That's why the dependency is ">0.2". Once the guzzelhttp/oauth-subscriber has a new release, the dependency will point to a specific release.

Regards,
Timo

**Comment by liberatomota-itcenter** [comment]
Working! 
Thank you
